[pytest]
pythonpath = .
testpaths = tests
markers =
    integration: marks tests as integration (deselect with '-m "not integration"')
addopts = -q -ra --strict-markers --strict-config
cache_dir = /tmp/pytest_cache
